# -*- coding: utf-8 -*-
"""movie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13NCwLpq8rTcsDvLLbkollzM5rrNusLxS
"""

import spacy
import numpy as np
nlp = spacy.load("en_core_web_sm")

#creating an empty dictionary
dictionary = {}

file = open("/movies.txt").read()
file = file.split('\n')
file.pop()
#saving contents of file in a dictionary
for i in file:
  dictionary[i.split(":")[0]] = i.split(":")[1]

list1 = []
for i in dictionary.values():
  sentence_to_compare = "Will he save their world or destroy it? When the Hulk becomes too dangerous for the Earth, the Illuminati trick Hulk into a shuttle and launch him into space to a planet where the Hulk can live in peace. Unfortunately, Hulk land on the planet Sakaar where he is sold into slavery and trained as a gladiator"

  model_sentences = nlp(sentence_to_compare)

  #comparing each movie description with the given description to find the best simillarity
  similarity = nlp(i).similarity(model_sentences)
  print(i + "-" + str(similarity))
  list1.append(similarity)

movie_title = []
for i in dictionary.keys():
  movie_title.append(i)

print(movie_title[list1.index(max(list1))])
